class_path: models.Spectral2DCNN
init_args:
  fe: log_mel_spec.yml
  kernel_size: [5, 7]
  out_channels: [64, 64, 64, 64, 64, 64]
  temp_dilations: [1, 2, 4, 16, 64, 128]
  pool_size: [2, 1]
  use_ln: true
  n_temp_params: 3
  temp_params_name: wt_pos
  temp_params_act_name: sigmoid
  global_param_names: []
  dropout: 0.25
  n_frames: 1500
  n_segments: 12
  degree: 3
  filter_depth: 2
  filter_width: 2
