seed_everything: 42

custom:
  project_name: acid_ddsp_2
  model_name: raw_mod__n_pos_2__lr_1e-2
  dataset_name: nsynth_strings_acoustic_val
  cpu_batch_size: 5  # For now must be >= n_examples
  use_wandb_cpu: false
  use_wandb_gpu: true

trainer:
  accelerator: gpu
  benchmark: false
  devices: [2]
  max_epochs: 100
  num_sanity_val_steps: 2
  accumulate_grad_batches: 1
  gradient_clip_val: 0.5

data:
  class_path: acid_ddsp.data_modules.NSynthStringsDataModule
  init_args:
    batch_size: 32
    ac: audio_config_wt.yml
    nsynth_strings_dir: ../data/nsynth_string_val
    num_workers: 4

model:
  class_path: acid_ddsp.lightning.PreprocLightningModule
  init_args:
    ac: audio_config_wt.yml
    spectral_visualizer: log_mel_spec.yml
#    log_envelope: true

    # use_model: false
    use_model: true
    model: spectral_2dcnn_wt.yml
    temp_params_name_hat: wt_pos
    synth_hat: synth_wt.yml

    loss_func: auraloss.freq.MultiResolutionSTFTLoss

optimizer: adam_w.yml
