seed_everything: 42

custom:
  project_name: acid_ddsp_2
  model_name: wt_4__filter_1x1__spline_36d3
#  model_name: fourier_8_bounded__n_pos_4__lr_5e-2_5e-3
  dataset_name: nsynth_vocal_synthetic_val__3s
#  dataset_name: nsynth_test__3s
  cpu_batch_size: 5  # For now must be >= n_examples
  use_wandb_cpu: false
  use_wandb_gpu: true

trainer:
  accelerator: gpu
  benchmark: false
  devices: [3]
  max_epochs: 100
  num_sanity_val_steps: 0
  accumulate_grad_batches: 1
  gradient_clip_val: 0.5

data:
  class_path: acid_ddsp.data_modules.NSynthDataModule
  init_args:
    batch_size: 32
    ac: audio_config_wt.yml
    data_dir: ../data/nsynth_vocal_synthetic_val
#    data_dir: ../data/nsynth_test
    num_workers: 4

model:
  class_path: acid_ddsp.lightning.PreprocLightningModule
  init_args:
    ac: audio_config_wt.yml
    spectral_visualizer: log_mel_spec.yml
#    log_envelope: true

    # use_model: false
    use_model: true
    model: spectral_2dcnn_wt.yml
    temp_params_name_hat: wt_pos
    synth_hat: synth_wt.yml

    loss_func: auraloss.freq.MultiResolutionSTFTLoss
    synth_opt: sf_adam_w__lr_5e-2.yml
    model_opt: sf_adam_w__lr_5e-3.yml

#optimizer: sf_adam_w.yml
#optimizer: sgd.yml
