class_path: data_modules.AudioConfig
init_args:
  sr: 48000
  buffer_size_seconds: 0.125
  note_on_duration: 0.125

  min_f0_hz: 32.70   # midi_f0 24
  max_f0_hz: 523.25  # midi_f0 72
  min_w_hz: 100.0
  max_w_hz: 8000.0

  stability_eps: 0.001
