class_path: data_modules.AudioConfig
init_args:
  sr: 44100
  buffer_size_seconds: 3.9996371882   # lol, to fit into 176,384 samples
  note_on_duration: 3.9996371882      # lol, to fit into 176,384 samples

  min_f0_hz: 32.70   # midi_f0 24
  max_f0_hz: 523.25  # midi_f0 72

  stability_eps: 0.001
