class_path: synths.WavetableSynth
init_args:
  ac: audio_config_wt.yml
  n_pos: 2
  n_wt_samples: 1024
  aa_filter_n: 129
#  wt_name: sines_2_1024.pt
  wt_name: sine_saw_1024.pt
  is_trainable: false
