seed_everything: 42

custom:
  project_name: acid_ddsp_2
#  model_name: cnn_ploss
  model_name: testing
  dataset_name: fixed_adsr__pointy
  cpu_batch_size: 5  # For now must be >= n_examples
  use_wandb_cpu: false
  use_wandb_gpu: true

trainer:
  accelerator: gpu
  benchmark: false
  devices: [4]
  max_epochs: 50
  num_sanity_val_steps: 0
  accumulate_grad_batches: 1
  gradient_clip_val: 0.5

data:
  class_path: acid_ddsp.data_modules.SynthDataModule
  init_args:
    batch_size: 64
    ac: audio_config_wt.yml
#    mod_sig_gen: mod_sig_gen.yml
    mod_sig_gen: mod_sig_gen__pointy.yml
#    train_n_per_epoch: 8000
    train_n_per_epoch: 15
#    val_n_per_epoch: 2000
    val_n_per_epoch: 10
    num_workers: 4
    temp_params_name: wt_pos

model:
  class_path: acid_ddsp.lightning.AcidDDSPLightingModule
  init_args:
    ac: audio_config_wt.yml
    spectral_visualizer: log_mel_spec.yml
#    log_envelope: true

    synth: synth_wt.yml
#    temp_params_name: wt_pos
#    global_param_names: []

    use_model: false
#    model: spectral_2dcnn_wt.yml
#    temp_params_name_hat: wt_pos
#    global_param_names_hat: []
    synth_hat: synth_wt.yml

    loss_func: auraloss.freq.MultiResolutionSTFTLoss
    use_p_loss: false
#    loss_func: torch.nn.MSELoss
#    use_p_loss: true

optimizer: adam_w.yml
