seed_everything: 42

custom:
  project_name: acid_ddsp
#  model_name: testing
#  model_name: cnn_ploss
  model_name: cnn_mss
  dataset_name: fixed_adsr__pointy
  cpu_batch_size: 64
  use_wandb_cpu: false
  use_wandb_gpu: true

trainer:
  accelerator: gpu
  benchmark: false
  devices: [1]
  max_epochs: 20
  num_sanity_val_steps: 1
  accumulate_grad_batches: 1
  gradient_clip_val: 0.5

data:
  class_path: acid_ddsp.data_modules.AcidDDSPDataModule
  init_args:
    batch_size: 64
    ac: audio_config.yml
#    mod_sig_gen: mod_sig_gen.yml
    mod_sig_gen: mod_sig_gen__pointy.yml
    train_n_per_epoch: 8000
#    train_n_per_epoch: 15
    val_n_per_epoch: 2000
#    val_n_per_epoch: 10
    num_workers: 4

model:
  class_path: acid_ddsp.lightning.AcidDDSPLightingModule
  init_args:
    ac: audio_config.yml
    spectral_visualizer: log_mel_spec.yml
    log_envelope: true

    synth: synth_lp_td.yml
    temp_params_name: w_mod_sig
    global_param_names: [ q, osc_shape, osc_gain, dist_gain ]

    model: spectral_2dcnn_coeff.yml
    temp_params_name_hat: logits
    global_param_names_hat: [ osc_shape, osc_gain, dist_gain ]
    synth_hat: synth_coeff_td.yml

#    model: spectral_2dcnn_lp.yml
#    temp_params_name_hat: w_mod_sig
#    global_param_names_hat: [ q, osc_shape, osc_gain, dist_gain ]
#    synth_hat: synth_lp_td.yml
#    synth_hat: synth_lstm_64.yml

    loss_func: auraloss.freq.MultiResolutionSTFTLoss
    use_p_loss: false
#    loss_func: torch.nn.MSELoss
#    use_p_loss: true

optimizer: adam_w.yml
