name: acid
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchaudio
  - torchvision
  - lightning
  - numba
  - cudatoolkit=11.8
  - pip:
    - auraloss
    - black
    - jsonargparse[signatures]
    - librosa
    - matplotlib=3.7.3
    - nnaudio
    - numpy=1.23.5
    - nvitop
    - pandas
    - tensorboard
    - wandb
