name: acid
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - auraloss
    - black
    - jsonargparse[signatures]
    - librosa
    - matplotlib
    - nnaudio
    - numba
    - numpy=1.23.5
    - pandas
    - torch
    - pytorch-lightning
    - torchaudio
    - torchvision
    - tensorboard
    - wandb
