class_path: feature_extraction.LogMelSpecFeatureExtractor
init_args:
  n_samples: 6000
  sr: 48000
  n_fft: 1024
  hop_len: 32
  n_mels: 128
  normalized: false
  center: true
  freq_mask_amount: 0.0
  time_mask_amount: 0.0
  eps: 1e-7
