class_path: data_modules.AudioConfig
init_args:
  sr: 48000
  buffer_size_seconds: 4.0
  note_on_duration: 3.0
  min_attack: 0.0
  max_attack: 1.0
  min_decay: 0.05
  max_decay: 1.0
  min_sustain: 0.1
  max_sustain: 1.0
  min_release: 0.0
  max_release: 2.0
