class_path: models.Spectral2DCNN
init_args:
  fe: log_mel_spec.yml
  kernel_size: [5, 7]
  out_channels: [64, 64, 64, 64, 64, 64]
  temp_dilations: [1, 4, 16, 64, 256, 512]
  pool_size: [2, 1]
  use_ln: true
  temp_params:
    add_lfo:
      dim: 1
      act: sigmoid
      adapt_dim: 0
      adapt_act: none
    sub_lfo:
      dim: 1
      act: sigmoid
      adapt_dim: 5
      adapt_act: none
  global_param_names: []
  dropout: 0.25
#  n_frames: 6001
#  n_segments: 48
  n_frames: 4501
  n_segments: 36
  degree: 3
