seed_everything: 42

custom:
  project_name: acid_ddsp_2
#  model_name: testing
#  model_name: wt_4__bezier_p12d3__lstm
#  model_name: wt_4_shan__bezier_p12d3__lstm
  model_name: wt_4_shan__bezier_no_splines__lstm
  dataset_name: serum_v1__BA_3s
#  dataset_name: serum_v1__BA_Angggeerrrrr
#  dataset_name: serum_v1__BA_Digimods
#  dataset_name: serum_v1__BA_DarkWobble
  cpu_batch_size: 5
  use_wandb_cpu: false
  use_wandb_gpu: true

trainer:
  accelerator: gpu
  benchmark: false
  devices: [7]
  max_epochs: 100
  num_sanity_val_steps: 1
  gradient_clip_val: 0.5
  accumulate_grad_batches: 1

data:
  class_path: acid_ddsp.data_modules.SerumDataModule
  init_args:
    batch_size: 16
    ac: audio_config.yml
    data_dir: ../data/serum-nsynth-v1
    preset_params_path: ../data/preset_params_v2.json
    num_workers: 4
    fname_keyword: "BA "
#    fname_keyword: "BA Angggeerrrrr 1999 [GI]"
#    fname_keyword: "BA DarkWobble [CFA]"
#    fname_keyword: "BA Digimods [ASL]"

model:
  class_path: acid_ddsp.lightning.PreprocLightningModule
  init_args:
    ac: audio_config.yml
    spectral_visualizer: log_mel_spec.yml
    log_envelope: true

    # use_model: false
    use_model: true
#    model: spectral_2dcnn.yml
#    synth_hat: synth.yml
#    model: spectral_2dcnn_shan.yml
    model: spectral_2dcnn_shan__no_splines.yml
    synth_hat: synth_shan.yml
    temp_param_names_hat: [add_lfo, sub_lfo]
    global_param_names_hat: [attack, decay, sustain, release]

    loss_func: auraloss.freq.MultiResolutionSTFTLoss
#    loss_func: jtfs_small.yml
#    loss_func: jtfs_dtfa.yml

    synth_opt: ../opt/sf_adam_w__lr_5e-2.yml
    model_opt: ../opt/sf_adam_w__lr_5e-3.yml

#optimizer: ../opt/sf_adam_w__lr_5e-3.yml
