seed_everything: 42

custom:
  project_name: acid_ddsp_2
#  model_name: testing
#  model_name: wt_8__filter_1x1__spline_8d3_knotsv3__adsr_linear
  model_name: wt_4__filter_1x1__spline_36d3__adsr_linear
#  dataset_name: serum_v1__5k
  dataset_name: serum_v1__3s_5k
  cpu_batch_size: 5
  use_wandb_cpu: false
  use_wandb_gpu: true

trainer:
  accelerator: gpu
  benchmark: false
  devices: [6]
  max_epochs: 100
  num_sanity_val_steps: 1
  gradient_clip_val: 0.5

  accumulate_grad_batches: 1

data:
  class_path: acid_ddsp.data_modules.SerumDataModule
  init_args:
    batch_size: 16
    ac: audio_config.yml
    data_dir: ../data/serum-nsynth-v1
    preset_params_path: ../data/preset_params_v2.json
    num_workers: 4

model:
  class_path: acid_ddsp.lightning.PreprocLightningModule
  init_args:
    ac: audio_config.yml
    spectral_visualizer: log_mel_spec.yml
    log_envelope: true

    # use_model: false
    use_model: true
    model: spectral_2dcnn.yml
    temp_param_names_hat: [add_lfo, sub_lfo]
    global_param_names_hat: [attack, decay, sustain, release]
    synth_hat: synth.yml

    loss_func: auraloss.freq.MultiResolutionSTFTLoss
#    loss_func: jtfs_small.yml
#    loss_func: jtfs_dtfa.yml

    synth_opt: ../opt/sf_adam_w__lr_5e-2.yml
    model_opt: ../opt/sf_adam_w__lr_5e-3.yml

#optimizer: ../opt/sf_adam_w__lr_5e-3.yml
