class_path: data_modules.AudioConfig
init_args:
#  sr: 44100
#  buffer_size_seconds: 0.136054421769
#  note_on_duration: 0.136054421769

  sr: 48000
  buffer_size_seconds: 0.125
  note_on_duration: -1

  min_attack: 0.001
  max_attack: 0.001
  min_decay: 0.125
  max_decay: 0.125
  min_sustain: 0.5
  max_sustain: 0.5
  min_release: 0.001
  max_release: 0.001
  min_alpha: 2.0
  max_alpha: 2.0

  min_f0_hz: 32.70   # midi_f0 24
  max_f0_hz: 523.25  # midi_f0 72
  min_w_hz: 100.0
  max_w_hz: 8000.0
  min_q: 0.7071
  max_q: 8.0
  min_dist_gain: 0.5
  max_dist_gain: 4.0
  min_osc_shape: 0.0
  max_osc_shape: 1.0
  min_osc_gain: 0.1
  max_osc_gain: 1.0
  stability_eps: 0.001
