class_path: data_modules.AudioConfig
init_args:
  sr: 48000

  buffer_size_seconds: 0.125
  note_on_duration: 0.100
  min_attack: 0.001
  max_attack: 0.001
  min_decay: 0.099
  max_decay: 0.099
  min_sustain: 0.5
  max_sustain: 0.5
  min_release: 0.025
  max_release: 0.025
  min_alpha: 2.0
  max_alpha: 2.0

#  buffer_size_seconds: 1.0
#  note_on_duration: 0.800
#  min_attack: 0.008
#  max_attack: 0.008
#  min_decay: 0.792
#  max_decay: 0.792
#  min_sustain: 0.5
#  max_sustain: 0.5
#  min_release: 0.200
#  max_release: 0.200
#  min_alpha: 2.0
#  max_alpha: 2.0

#  buffer_size_seconds: 0.125
#  note_on_duration: 0.100
#  min_attack: 0.001
#  max_attack: 0.050
#  min_decay: 0.001
#  max_decay: 0.100
#  min_sustain: 0.1
#  max_sustain: 1.0
#  min_release: 0.001
#  max_release: 0.050
#  min_alpha: 0.1
#  max_alpha: 6.0

  min_f0_hz: 32.70   # midi_f0 24
  max_f0_hz: 523.25  # midi_f0 72
  min_w_hz: 100.0
  max_w_hz: 8000.0
  min_q: 0.7071
  max_q: 8.0
#  min_q: 6.0
#  max_q: 6.0
  min_dist_gain: 1.0
  max_dist_gain: 3.0
  min_osc_shape: 0.0
  max_osc_shape: 1.0
  osc_audio_gain: 0.5
  stability_eps: 0.001
