class_path: models.AudioTCN
init_args:
  in_channels: 1
  out_channels: [84, 84, 84, 84, 84, 84, 84, 84, 84]
  kernel_size: 11
  dilations: [1, 2, 4, 8, 16, 32, 64, 128, 256]
  padding: same
  padding_mode: reflect
  act_name: prelu
