seed_everything: 42

custom:
  project_name: acid_ddsp
#  model_name: testing
#  model_name: cnn_mel_spec_ploss
  model_name: cnn_mel_spec_mss
  dataset_name: cfq__f0_24_72__fixed_adsr
#  dataset_name: cfq_pointy__f0_24_72__fixed_adsr
  cpu_batch_size: 3
  use_wandb_cpu: false
  use_wandb_gpu: true

trainer:
  accelerator: gpu
  benchmark: false
  devices: [7]
  max_epochs: 20
  num_sanity_val_steps: 0
  accumulate_grad_batches: 1

data:
  class_path: acid_ddsp.data_modules.AcidDDSPDataModule
  init_args:
    batch_size: 64
    ac: ../configs/audio_config.yml
    mod_sig_gen: ../configs/mod_sig_gen.yml
#    mod_sig_gen: ../configs/mod_sig_gen__pointy.yml
    train_n_per_epoch: 8000
#    train_n_per_epoch: 9
    val_n_per_epoch: 2000
#    val_n_per_epoch: 9
    num_workers: 4

model:
  class_path: acid_ddsp.lightning.AcidDDSPLightingModule
  init_args:
    ac: ../configs/audio_config.yml
    model: ../configs/spectral_2dcnn.yml
#    model: ../configs/audio_tcn.yml
#    loss_func: torch.nn.L1Loss
#    loss_func: torch.nn.MSELoss
#    loss_func: auraloss.time.ESRLoss
    loss_func: auraloss.freq.MultiResolutionSTFTLoss
#    loss_func: ../configs/rand_mss.yml
    use_p_loss: false

#    use_p_loss: true
#    loss_func: torch.nn.L1Loss
#    loss_func: torch.nn.MSELoss
#    loss_func: auraloss.time.ESRLoss

    log_envelope: false
    spectral_visualizer: ../configs/log_mel_spec.yml

optimizer: ../configs/adam_w.yml
