seed_everything: 42

custom:
  project_name: acid_ddsp
#  model_name: testing
#  model_name: cnn_mss_lp
#  model_name: cnn_mss_lp_fsm_512_32_1
#  model_name: cnn_mss_lp_fsm_1024_32_1
  model_name: cnn_mss_lp_fsm_2048_32_1
#  model_name: cnn_mss_lp_fsm_4096_32_1
#  model_name: cnn_mss_lstm64
  dataset_name: abstract_303_48k__6k__4k_min
  cpu_batch_size: 5  # For now must be >= n_examples
#  cpu_batch_size: 32  # For now must be >= n_examples
  use_wandb_cpu: false
  use_wandb_gpu: true

trainer:
  accelerator: gpu
  benchmark: false
  devices: [6]
  max_epochs: 200
  num_sanity_val_steps: 0
  accumulate_grad_batches: 1
#  check_val_every_n_epoch: 1
  check_val_every_n_epoch: 8
  gradient_clip_val: 0.5

data:
  class_path: data_modules.PreprocDataModule
  init_args:
    batch_size: 34
    ac: ../configs/audio_config_abstract_303.yml
    data_dir: ../data/abstract_303_48k__6k__4k_min
    ext: .wav
    val_split: 0.2
    test_split: 0.2
    split_seed: 42
    num_workers: 4

model:
  class_path: lightning.PreprocLightningModule
  init_args:
    ac: ../configs/audio_config_abstract_303.yml

#    model: ../configs/spectral_2dcnn_logits5.yml
#    synth_hat_type: AcidSynthLearnedBiquadCoeff

#    model: ../configs/spectral_2dcnn_logits5.yml
#    synth_hat_type: AcidSynthLearnedBiquadCoeffFSM
#    synth_hat_kwargs:
#      win_len: 512
#      overlap: 0.9375  # 32 samples at 512
##      win_len: 1024
##      overlap: 0.96875  # 32 samples at 1024
##      win_len: 2048
##      overlap: 0.984375  # 32 samples at 2048
##      win_len: 4096
##      overlap: 0.9921875  # 32 samples at 4096
#      oversampling_factor: 1

#    model: ../configs/spectral_2dcnn.yml
#    synth_hat_type: AcidSynthLPBiquad

    model: ../configs/spectral_2dcnn.yml
    synth_hat_type: AcidSynthLPBiquadFSM
    synth_hat_kwargs:
#      win_len: 512
#      overlap: 0.9375  # 32 samples at 512
#      win_len: 1024
#      overlap: 0.96875  # 32 samples at 1024
      win_len: 2048
      overlap: 0.984375  # 32 samples at 2048
#      win_len: 4096
#      overlap: 0.9921875  # 32 samples at 4096
      oversampling_factor: 1

#    model: ../configs/spectral_2dcnn.yml
#    synth_hat_type: AcidSynthLSTM
#    synth_hat_kwargs:
#      n_hidden: 64

#    loss_func: torch.nn.L1Loss
#    loss_func: torch.nn.MSELoss
#    loss_func: auraloss.time.ESRLoss
#    loss_func: ../configs/rand_mss.yml
    loss_func: auraloss.freq.MultiResolutionSTFTLoss
    use_p_loss: false

    log_envelope: true
    spectral_visualizer: ../configs/log_mel_spec.yml
#    synth_eval_type: AcidSynthLearnedBiquadCoeff
    synth_eval_type: AcidSynthLPBiquad

    fad_model_names:
      - clap-2023
      - encodec-emb
      - wavlm-base

optimizer: ../configs/adam_w.yml
