seed_everything: 42

custom:
  project_name: acid_ddsp
#  model_name: cnn_ploss
  model_name: cnn_l1
  dataset_name: midi36_fixed_adsr
  cpu_batch_size: 5
  use_wandb_cpu: false
  use_wandb_gpu: true

trainer:
  accelerator: gpu
  benchmark: false
  devices: [6]
  max_epochs: 50
  num_sanity_val_steps: 0
  accumulate_grad_batches: 1

data:
  class_path: acid_ddsp.data_modules.AcidDDSPDataModule
  init_args:
    batch_size: 128
    ac: ../configs/audio_config.yml
    mod_sig_gen: ../configs/mod_sig_gen.yml
    train_n_per_epoch: 8000
    val_n_per_epoch: 2000
    num_workers: 4

model:
  class_path: acid_ddsp.lightning.AcidDDSPLightingModule
  init_args:
    ac: ../configs/audio_config.yml
    model: ../configs/spectral_2dcnn.yml
    loss_func: torch.nn.L1Loss
#    loss_func: torch.nn.MSELoss
#    loss_func: auraloss.freq.MultiResolutionSTFTLoss
#    use_p_loss: true
    use_p_loss: false

optimizer: ../configs/adam_w.yml
