class_path: data_modules.AudioConfig
init_args:
  sr: 16000
  buffer_size_seconds: 4.0
  note_on_duration: 4.0

  min_f0_hz: 32.70   # midi_f0 24
  max_f0_hz: 523.25  # midi_f0 72

  stability_eps: 0.001
