class_path: models.Spectral2DCNN
init_args:
  fe: log_mel_spec_dd50.yml
  in_ch: 3
  kernel_size: [5, 7]
  out_channels: [64, 64, 64, 64, 64, 64]
#  temp_dilations: [1, 4, 16, 64, 256, 512]
  temp_dilations: [1, 4, 16, 32, 64, 128]
  pool_size: [2, 1]
  use_ln: true
  temp_params:
    sub_lfo:
      dim: 1
      act: none
      is_spline: true
      n_segments: 12
      degree: 3
      is_bounded: false
      adapt_dim: 5
      adapt_act: none
      adapt_use_latent: true
      adapt_use_separate: true
#      adapt_use_latent: false
#    sub_lfo:
#      #      dim: 1
#      dim: 5
#      #      act: none
#      act: sigmoid
#      adapt_dim: 5
#      #      adapt_dim: 0
#      adapt_act: none
#    spline_0:
#      dim: 1
#      act: none
#      adapt_dim: 0
#      adapt_act: none
#    spline_1:
#      dim: 1
#      act: none
#      adapt_dim: 0
#      adapt_act: none
#    spline_2:
#      dim: 1
#      act: none
#      adapt_dim: 0
#      adapt_act: none
#    spline_3:
#      dim: 1
#      act: none
#      adapt_dim: 0
#      adapt_act: none
#    spline_4:
#      dim: 1
#      act: none
#      adapt_dim: 0
#      adapt_act: none
  global_param_names: []
  dropout: 0.25
  n_frames: 1501
