class_path: synths.ComposableSynth
init_args:
  ac: audio_config.yml
  add_synth_module: wavetable_osc_ableton.yml
  sub_synth_module: filter_coeff_logits.yml
  sub_lfo_name: sub_lfo_adapted
#  sub_lfo_name: sub_lfo
