custom:
  project_name: acid_ddsp_2
  model_name: mss__frame
  dataset_name: ableton__ase
  cpu_batch_size: 5  # For now must be >= n_examples
  use_wandb_cpu: false
  use_wandb_gpu: false

trainer:
  accelerator: gpu
  benchmark: false
  devices: [4]
  max_epochs: 50
  num_sanity_val_steps: 1
  accumulate_grad_batches: 1
  gradient_clip_val: 0.5

data:
  class_path: acid_ddsp.data_modules.SeedDataModule
  init_args:
    batch_size: 32
    ac: audio_config.yml
    n_seeds: 1024
    mod_sig_gens:
      - class_path: modulations.ModSignalGenRandomBezier
        init_args:
          min_n_seg: 1
          max_n_seg: 8
          min_degree: 1
          max_degree: 3
          min_seg_interval_frac: 0.25
          softmax_tau: 0.25
    temp_param_names:
      - add_lfo
      - sub_lfo
      - env
    num_workers: 4

model:
  class_path: acid_ddsp.lightning.AcidDDSPLightingModule
  init_args:
    ac: audio_config.yml
    spectral_visualizer: log_mel_spec.yml

    synth: synth_ase.yml
    temp_param_names:
      - add_lfo
      - sub_lfo
      - env

    use_model: true
    model: spectral_2dcnn_dd50__ase_frame.yml
    temp_param_names_hat:
      - add_lfo
      - sub_lfo
      - env
    synth_hat: synth_ase.yml

    loss_func: auraloss.freq.MultiResolutionSTFTLoss
    use_p_loss: false
#    use_p_loss: true
#    loss_func: torch.nn.MSELoss

    run_name: mss__frame__ableton__ase

optimizer: ../opt/adam_w__lr_1e-3.yml
