seed_everything: 42

custom:
  project_name: acid_ddsp_2
#  model_name: ploss__framewise
#  model_name: mss__framewise
  model_name: ploss__s12d3
#  model_name: mss__s12d3
#  dataset_name: add_lfo__sin_saw_256
#  dataset_name: add_lfo__ableton__split_rand_train_seed
  dataset_name: add_lfo__waveedit
  cpu_batch_size: 5  # For now must be >= n_examples
  use_wandb_cpu: false
#  use_wandb_cpu: true
  use_wandb_gpu: true

trainer:
  accelerator: gpu
  benchmark: false
  devices: [6]
  max_epochs: 1
  num_sanity_val_steps: 1
  accumulate_grad_batches: 1
  gradient_clip_val: 0.5

data:
  class_path: acid_ddsp.data_modules.SeedDataModule
  init_args:
    batch_size: 32
    ac: audio_config.yml
    n_seeds: 25
#    mod_sig_gen: mod_sig_gen.yml
    mod_sig_gen: mod_sig_gen__pointy.yml
    temp_param_names:
      - add_lfo
#      - env
    num_workers: 4

model:
  class_path: acid_ddsp.lightning.AcidDDSPLightingModule
  init_args:
    ac: audio_config.yml
    spectral_visualizer: log_mel_spec.yml

    synth: synth.yml
    temp_param_names:
      - add_lfo
#      - env

#    use_model: false
    use_model: true
    model: spectral_2dcnn.yml
    temp_param_names_hat:
      - add_lfo
#      - env
    synth_hat: synth.yml

#    loss_func: auraloss.freq.MultiResolutionSTFTLoss
#    use_p_loss: false
    use_p_loss: true
    loss_func: torch.nn.MSELoss

#optimizer: ../opt/adam_w__lr_1e-2.yml
optimizer: ../opt/adam_w__lr_1e-3.yml
