seed_everything: 42

custom:
  project_name: acid_ddsp_2
  model_name: testing
  dataset_name: testing
  cpu_batch_size: 5  # For now must be >= n_examples
  use_wandb_cpu: false
  use_wandb_gpu: true

trainer:
  accelerator: gpu
  benchmark: false
  devices: [3]
  max_epochs: 100
  num_sanity_val_steps: 2
  accumulate_grad_batches: 1
  gradient_clip_val: 0.5

data:
  class_path: acid_ddsp.data_modules.WavetableDataModule
  init_args:
    batch_size: 64
    ac: audio_config.yml
    wt_dir: ../data/wavetables/ableton
    n_seeds_per_wt: 5
#    mod_sig_gen: mod_sig_gen.yml
    mod_sig_gen: mod_sig_gen__pointy.yml
    temp_param_names:
      - add_lfo
    num_workers: 4

model:
  class_path: acid_ddsp.lightning.AcidDDSPLightingModule
  init_args:
    ac: audio_config.yml
    spectral_visualizer: log_mel_spec.yml

    synth: synth.yml
    temp_param_names:
      - add_lfo

#    use_model: false
    use_model: true
    model: spectral_2dcnn.yml
    temp_param_names_hat:
      - add_lfo
    synth_hat: synth.yml

    loss_func: auraloss.freq.MultiResolutionSTFTLoss
    use_p_loss: false

optimizer: ../opt/adam_w__lr_1e-3.yml
#optimizer: sgd.yml
